name: Pull Image from Docker Hub on Server Instance

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.userApp
          push: true
          tags: arvindpro/paytm_user_app:latest # Replace with your Docker Hub username and repository

      - name: Verify Pushed Image
        run: docker pull arvindpro/paytm_user_app:latest # Replace with your Docker Hub username and repository
      
      - name: Apply all pending migrations to the database
        if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'prisma/migrations/')
        run: |
          cd /app/packages/db
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull arvindpro/paytm_user_app:latest
            sudo docker stop paytm-app || true
            sudo docker rm paytm-app || true
            sudo docker run -d --name paytm-app --restart unless-stopped -p 3000:3000 -e DATABASE_URL=${{ secrets.DATABASE_URL }} arvindpro/paytm_user_app:latest
